/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fi_aalto_ssg_opentee_openteeandroid_LibteeWrapper */

#ifndef _Included_fi_aalto_ssg_opentee_openteeandroid_LibteeWrapper
#define _Included_fi_aalto_ssg_opentee_openteeandroid_LibteeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fi_aalto_ssg_opentee_openteeandroid_LibteeWrapper
 * Method:    teecInitializeContext
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_fi_aalto_ssg_opentee_openteeandroid_LibteeWrapper_teecInitializeContext
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     fi_aalto_ssg_opentee_openteeandroid_LibteeWrapper
 * Method:    teecFinalizeContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fi_aalto_ssg_opentee_openteeandroid_LibteeWrapper_teecFinalizeContext
  (JNIEnv *, jclass);

/*
 * Class:     fi_aalto_ssg_opentee_openteeandroid_LibteeWrapper
 * Method:    teecRegisterSharedMemory
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_fi_aalto_ssg_opentee_openteeandroid_LibteeWrapper_teecRegisterSharedMemory
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
